baseurl = "https://blog.sanyamkapoor.com/"
languageCode = "en-us"
title = "Sanyam Kapoor"
canonifyurls = true
theme = "cactus"
disqusShortname = "activatedgeek"

[params]
  name = "Sanyam Kapoor"
  description = "Programmer - Blogger - DevOps"
  bio = "Programmer - Blogger - DevOps"
  twitter = "activatedgeek"
  enableRSS = true
  readMore = ""
  copyright = "&copy; Sanyam Kapoor"
  socialIconStyle = "circle"

[social]
  twitterbird = "https://www.twitter.com/activatedgeek"
  githubalt = "https://www.github.com/activatedgeek"
  linkedin = "https://in.linkedin.com/in/sanyamkapoor"
  quora = "https://www.quora.com/profile/Sanyam-Kapoor"
