language: go

services:
  - docker

dist: xenial

env:
  global:
    - DISTILLPUB_THEME_VERSION=0.6.0
    - NETLIFYCTL_VERSION=0.4.0
    - HUGO_VERSION=0.58.3

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: (type != pull_request AND branch = master)

jobs:
  include:
    - stage: test
      before_script:
        - curl -LO https://github.com/activatedgeek/distillpub/tarball/${DISTILLPUB_THEME_VERSION} && tar -xzvf ${DISTILLPUB_THEME_VERSION} && mv *distillpub* themes/distillpub
        - curl -LO https://github.com/netlify/netlifyctl/releases/download/v${NETLIFYCTL_VERSION}/netlifyctl-linux-amd64-${NETLIFYCTL_VERSION}.tar.gz && tar -xzvf *.tar.gz && rm *.tar.gz
        - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb && sudo dpkg -i *.deb && rm *.deb
        - pip install --user -r requirements.txt
        - hugo version && pygmentize -V && ./netlifyctl version
      script:
        - make public
      after_success:
        - ./netlifyctl deploy -A ${NETLIFY_ACCESS_TOKEN} -m "${TRAVIS_COMMIT_MESSAGE}" -d
    
    - stage: deploy
      before_script:
        - curl -LO https://github.com/activatedgeek/distillpub/tarball/${DISTILLPUB_THEME_VERSION} && tar -xzvf ${DISTILLPUB_THEME_VERSION} && mv *distillpub* themes/distillpub
        - curl -LO https://github.com/netlify/netlifyctl/releases/download/v${NETLIFYCTL_VERSION}/netlifyctl-linux-amd64-${NETLIFYCTL_VERSION}.tar.gz && tar -xzvf *.tar.gz && rm *.tar.gz
        - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb && sudo dpkg -i *.deb && rm *.deb
        - pip install --user -r requirements.txt
        - hugo version && pygmentize -V && ./netlifyctl version
      script:
        - git clone https://${GH_ACCESS_TOKEN}@github.com/activatedgeek/cv
        - docker run --rm -u $(id -u):$(id -g) -v$(pwd)/cv:/cv -w /cv jgoldfar/latex-docker:alpine-minplus-latest sh -c make all
        - mv cv/dist/*.pdf static/files
        - make public
      after_success:
        - ./netlifyctl deploy -A ${NETLIFY_ACCESS_TOKEN} -m "${TRAVIS_COMMIT_MESSAGE}"
