language: go

sudo: required

dist: xenial

install:
  - curl -LO https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19-64bit.deb && sudo dpkg -i hugo_0.19-64bit.deb
  - sudo apt -qq update && sudo apt install -y --no-install-recommends python python-pip texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
  - sudo pip install Pygments

script:
  # Build latest CV
  - cd cv && mkdir build && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build CV.tex && cd ..
  # Add CV to static content
  - mkdir -p static/files && mv cv/build/CV.pdf static/files
  # Build blog
  - hugo version && hugo -v

# deploy:
#   # Deploy to Github Releases
#   provider: releases
#   api_key: '$GITHUB_ACCESS_TOKEN'
#   file:
#     - 'cv/build/CV.pdf'
#   skip_cleanup: true
#   on:
#     tags: true

after_success:
  - npm i netlify-cli -g
  # Deploy to Netlify
  - netlify deploy -t $NETLIFY_ACCESS_TOKEN -s $NETLIFY_SITE_ID -p public
