language: go

sudo: required

dist: trusty

install:
  - make install

before_script:
  - pdflatex --version
  - pygmentize -V
  - hugo version
  - ./netlifyctl version

script:
  # Build Resume and SOP
  - git clone https://$GH_ACCESS_TOKEN@github.com/activatedgeek/resume
  - cd resume && make all && cd ..
  - mv resume/dist/*.pdf static/files
  # Build Website
  - make public

after_success:
  - make deploy
