language: go

sudo: required

dist: trusty

install:
  - make install

before_script:
  - pdflatex --version
  - pygmentize -V
  - hugo version
  - ./netlifyctl version

script:
  - cd cv && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build resume.tex && cd ..
  - cd cv && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build SOP_NYU_Courant.tex && cd ..
  - mv cv/build/*.pdf static/files
  - hugo -v
  - cp _redirects public/

after_success:
  - ./netlifyctl deploy -A $NETLIFY_ACCESS_TOKEN
