language: go

sudo: required

dist: trusty

install:
  - curl -LO https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17-64bit.deb && sudo dpkg -i hugo_0.17-64bit.deb
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

script:
  # Build latest CV
  - cd cv && mkdir build && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build CV.tex && cd ..
  # Add CV to static content
  - mkdir -p static/files && mv cv/build/CV.pdf static/files/cv_latest.pdf
  # Build blog
  - hugo version && hugo -v

# deploy:
#   # Deploy to Github Releases
#   provider: releases
#   api_key: '$GITHUB_ACCESS_TOKEN'
#   file:
#     - 'cv/build/CV.pdf'
#   skip_cleanup: true
#   on:
#     tags: true

after_success:
  - npm i netlify-cli -g
  # Deploy to Netlify
  - netlify deploy -t $NETLIFY_ACCESS_TOKEN -s $NETLIFY_SITE_ID -p public
