language: go

sudo: required

dist: trusty

install:
  - make install

before_script:
  - pdflatex --version
  - pygmentize -V
  - hugo version
  - ./netlifyctl version

script:
  - make public

after_success:
  - make deploy
