language: go

sudo: required

dist: trusty

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.25.1/hugo_0.25.1_Linux-64bit.deb && sudo dpkg -i hugo_0.25.1_Linux-64bit.deb
  - curl -LO https://github.com/netlify/netlifyctl/releases/download/v0.1.4/netlifyctl-linux-amd64.tar.gz && tar -xzvf netlifyctl-linux-amd64.tar.gz
  # - sudo apt-get install textlive-full
  - sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
  - sudo pip install -r requirements.txt

before_script:
  - pdflatex --version
  - pygmentize -V
  - hugo version
  - ./netlifyctl version
  - mkdir -p cv/build static/files

script:
  - cd cv && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build CV.tex && cd ..
  - cd cv && pdflatex -interaction=nonstopmode -halt-on-error -output-directory build SOP_NYU_Courant.tex && cd ..
  - mv cv/build/*.pdf static/files
  - hugo -v

after_success:
  - ./netlifyctl deploy -A $NETLIFY_ACCESS_TOKEN
