baseURL: 'https://www.sanyamkapoor.com'
theme: even
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: friendly
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml
blackfriday:
  hrefTargetBlank: true

disqusShortname: sanyamkapoor
googleAnalytics: UA-87707145-1

title: Sanyam Kapoor
author:
  name: Sanyam Kapoor

menu:
  main:
    - name: Tags
      weight: 20
      identifier: tags
      url: /tags
    - name: Categories
      weight: 30
      identifier: categories
      url: /categories
    - name: Résumé
      weight: 40
      identifier: resume
      url: /files/resume.pdf

params:
  version: 3.x
  since: '2015'
  logoTitle: Sanyam Kapoor
  dateFormatToUse: 'Mon, Jan 2 2006'
  moreMeta: true
  toc: true
  highlightjs: true
  customCSS: []
  customJS: []
  social:
    a.ai.google-scholar: 'https://scholar.google.com/citations?user=p0NMtgsAAAAJ'
    b.fa.github: 'https://github.com/activatedgeek'
    c.fa.hacker-news: 'https://news.ycombinator.com/user?id=activatedgeek'
    d.fa.linkedin: 'https://linkedin.com/in/sanyamkapoor'
    e.fa.stack-overflow: 'https://stackoverflow.com/users/2425365'
    f.fa.twitter: 'https://twitter.com/activatedgeek'
