---
baseurl: '/'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
PygmentsCodeFences: true
PygmentsStyle: emacs

#disqusShortname: sanyamkapoor
googleAnalytics: UA-87707145-1

author: Sanyam Kapoor
title: Sanyam Kapoor
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  intro: Sanyam Kapoor
  description: Engineer, Cognitive Systems Enthusiast, About Boring Technologies, Automation First
  authorImage: headshot.jpg
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  travisRepo: activatedgeek/website
  extra:
    copyright: '&copy; 2017. Sanyam Kapoor.'
    poweredBy: true
    highlightJS: true
  social:
    github: activatedgeek
    stackoverflow: 2425365
    hackernews: activatedgeek
    quora: Sanyam-Kapoor
    angellist: sanyam-kapoor
    linkedin: sanyamkapoor
    twitter: activatedgeek
    facebook: activatedgeek
    email: 42@sanyamkapoor.com
  menu:
    main:
      - name: blog
        identifier: blog
        url: /blog
        weight: 1
      - name: guides
        identifier: guides
        url: /guides
        weight: 2
      - name: problems
        url: /problems
        identifier: problems
        weight: 3
      - name: cv
        identifier: cv
        url: /files/CV.pdf
        weight: 4
