---
baseurl: '/'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml

disqusShortname: sanyamkapoor
googleAnalytics: UA-87707145-1

author: Sanyam Kapoor
title: Sanyam Kapoor
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  author: Sanyam Kapoor
  intro: Engineer, Cognitive Systems Enthusiast
  # description:
  authorImage: headshot.jpg
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  travisRepo: activatedgeek/website
  extra:
    copyright: '&copy; 2016. Sanyam Kapoor.'
    poweredBy: true
    highlightJS: true
  social:
    github: activatedgeek
    stackoverflow: 2425365
    hackernews: activatedgeek
    # quora: Sanyam-Kapoor
    linkedIn: sanyamkapoor
    twitter: activatedgeek
    facebook: activatedgeek
    email: hello@sanyamkapoor.com
  menu:
    main:
      - name: blog
        identifier: posts
        url: /blog
      - name: cv
        url: /files/cv_latest.pdf
