---
baseURL: 'https://www.sanyamkapoor.com'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: emacs

googleAnalytics: UA-87707145-1

author: Sanyam Kapoor
title: Sanyam Kapoor
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  intro: Sanyam Kapoor
  description: Computer Vision Researcher, About Boring Technologies, Automation First
  authorImage: https://graph.facebook.com/10203983748456800/picture?type=large
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  travisRepo: activatedgeek/website
  extra:
    copyright: '&copy; 2017. Sanyam Kapoor.'
    poweredBy: true
    facebookAppId: 1115424195239714
  social:
    github: activatedgeek
    stackoverflow: 2425365
    hackernews: activatedgeek
    quora: Sanyam-Kapoor
    angellist: sanyam-kapoor
    linkedin: sanyamkapoor
    twitter: activatedgeek
    facebook: activatedgeek
    email: 42@sanyamkapoor.com
  menu:
    main:
      - name: blog
        identifier: blog
        url: /blog
        weight: 1
      - name: computer vision
        identifier: computer-vision
        url: /cv
        weight: 2
      - name: guides
        identifier: guides
        url: /guides
        weight: 3
      - name: problems
        url: /problems
        identifier: problems
        weight: 4
      - name: cv
        identifier: cv
        url: /files/CV.pdf
        weight: 5
