---
baseURL: 'https://www.sanyamkapoor.com'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: emacs

googleAnalytics: UA-87707145-1
disqusShortname: sanyamkapoor

author: Sanyam Kapoor
title: Sanyam Kapoor
theme: goa

blackfriday:
  hrefTargetBlank: true

params:
  intro: Sanyam Kapoor
  description: do you generalize well?
  authorImage: https://graph.facebook.com/10203983748456800/picture?type=large
  enableRSS: true
  dateFormat: 'Jan 2, 2006'
  travisRepo: activatedgeek/website
  extra:
    poweredBy: true
    facebookProfileId: 10203983748456800
  social:
    github: activatedgeek
    stackoverflow: 2425365
    hackernews: activatedgeek
    quora: Sanyam-Kapoor
    linkedin: sanyamkapoor
    twitter: activatedgeek
  menu:
    main:
      - name: blog
        identifier: blog
        url: /blog
        weight: 1
      - name: machine learning
        identifier: machine learning
        url: /machine-learning
        weight: 2
      - name: problem solving
        url: /problem-solving
        identifier: problem solving
        weight: 3
      - name: résumé
        identifier: resume
        url: /files/resume.pdf
        weight: 4
