baseURL: 'https://www.sanyamkapoor.com'
theme: even
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml
pygmentsCodeFences: true
pygmentsStyle: friendly
sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

disqusShortname: sanyamkapoor
googleAnalytics: UA-87707145-1

title: Sanyam Kapoor
author:
  name: Sanyam Kapoor

menu:
  main:
    - name: Home
      weight: 10
      identifier: home
      url: /
    - name: Résumé
      weight: 30
      identifier: resume
      url: /files/resume.pdf

params:
  version: 3.x
  since: '2015'
  logoTitle: Sanyam Kapoor
  dateFormatToUse: 'Mon, Jan 2 2006'
  moreMeta: true
  toc: true
  highlightjs: true
  customCSS: []
  customJS: []
  social:
    b-stack-overflow: 'http://localhost:1313'
    c-twitter: 'http://localhost:1313'
    e-linkedin: 'http://localhost:1313'
    g-github: 'http://localhost:1313'
