[build]
  publish = "public/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "15"
  RUBY_VERSION = "2.7.1"
  YARN_VERSION = "1.22.10"
  GATSBY_GC_CODE = "imbayes"
  LIBRARYTHING_USERID = "activatedgeek"
