---
baseurl: '/'
relativeURLs: true
canonifyurls: true
enableRobotsTXT: true
languageCode: en-us
metaDataFormat: yaml

title: Sanyam Kapoor
theme: cactus
disqusShortname: activatedgeek

blackfriday:
  hrefTargetBlank: true

params:
  name: Sanyam Kapoor
  description: Programmer - Blogger - DevOps
  bio: Programmer - Blogger - DevOps
  twitter: activatedgeek
  enableRSS: true
  copyright: '&copy; Sanyam Kapoor'
  socialIconStyle: circle
  version: 1.0.6

social:
  twitterbird: https://www.twitter.com/activatedgeek
  githubalt: https://www.github.com/activatedgeek
  linkedin: https://in.linkedin.com/in/sanyamkapoor
  quora: https://www.quora.com/profile/Sanyam-Kapoor
