#!/usr/bin/env bash

if [[ -z "${1}" ]]; then
  echo "Missing file name!"
  exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pushd "${DIR}/.."

CONTENT_DIR="site/contents"
BASE_DIR=$(dirname ${1})

mkdir -p "${CONTENT_DIR}/${BASE_DIR}"

cat << EOF > "${CONTENT_DIR}/${1}"
---
title:
description:
date: $(date +"%b %d %Y, %H:%M %z")
area:
cat:
---
EOF

popd
